# Uncomment the next line to define a global platform for your project
  platform :ios, '9.0'

target 'display' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for display
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'FirebaseUI/Auth'
  pod 'FirebaseUI/Google'	
  pod 'Firebase/Storage'
  pod 'NVActivityIndicatorView'

pod 'Firestore', :podspec => 'https://storage.googleapis.com/firebase-preview-drop/ios/firestore/0.7.0/Firestore.podspec.json'

  target 'displayTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'displayUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
